export const HotstarList=[
    {
      imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/3934/1083934-v-3c2b3f7e195b",
      name:'Latest',

    },{
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/3022/1083022-v-90c34f714f7a",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/473/1080473-v-d97e637cb29d",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/473/1080473-v-d97e637cb29d",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/3869/1083869-v-cf73d8947672",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4290/1074290-v-3d1de5d1c0e3",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/8804/1068804-v-900825dcd2d0",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/8857/1068857-v-d30bc5e504a4",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/3207/1063207-v-1b046084c692",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/9895/1059895-v-bc89231f8f01",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/5472/1055472-v-4fac4c4e1978",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/6097/1056097-v-36f647f17cee",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/2944/1052944-v-0ed37e31f3a3",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/8632/1048632-v-380ed721403f",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/1472/1051472-v-34c24c5361ee",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/5763/1045763-v-1d9f41f00c89",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/1684/1011684-v-374e17c7e183",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/2213/1042213-v-1416e8e25397",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/3029/1033029-v-bd928a1dd530",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/1443/1041443-v-d54a72e03146",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/8256/1038256-v-59a659b25342",
        name:'Latest',
  
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/3126/1003126-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/748/1000748-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/3423/753423-h",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/3556/753556-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/3795/673795-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/6731/676731-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/6692/736692-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/7373/697373-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/7861/677861-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/7825/677825-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/6743/676743-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/6743/676743-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/6752/676752-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/7850/677850-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/7835/677835-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/7839/677839-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/7845/677845-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/7858/677858-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/6748/676748-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/6736/676736-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/6715/676715-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/6708/676708-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/2459/792459-v",
        name:'Cartoon',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/3779/673779-v",
        name:'Cartoon',
      },  
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/3774/673774-v",
        name:'Cartoon',
      }, 
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/3767/673767-v",
        name:'Cartoon',
      }, 
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/4492/674492-v",
        name:'Cartoon',
      }, 
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/3698/673698-v",
        name:'Cartoon',
      },   
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/1691/1011691-v-657881703c09",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/6365/936365-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/1258/911258-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/5157/875157-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/7809/877809-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/5180/875180-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/5190/875190-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/5167/875167-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4463/674463-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4580/674580-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4483/674483-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4583/674583-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4672/674672-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4622/674622-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4672/674672-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4622/674622-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/4432/674432-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/4631/674631-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_1_5x/sources/r1/cms/prod/4511/674511-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4571/674571-v",
        name:'Superheroes',
      },
      {
        imgsrc:"https://img1.hotstarext.com/image/upload/f_auto,t_web_vl_3x/sources/r1/cms/prod/4411/674411-v",
        name:'Superheroes'
      }
    ]